# Fuse Version and Patch
fuse:
    version: '6.3.0'
    patch: '254'

# OS User to install/execute Fuse
user:
  name: 'fuse'
  shell: '/bin/bash'
  homedir: 'True'

# OS Global Variables

# Java Home
JAVA_HOME: /usr/lib/jvm/jre-1.8.0-openjdk

# Fuse Home
FUSE_HOME: '/opt/fuse/latest-{{ esb_name }}'

# Fuse Administrative Users
fuse_users:
    admin:
      username: admin
      password: karaf
      roles:
        - admin
        - manager
        - viewer
        - Monitor
        - Operator
        - Maintainer
        - Deployer
        - Auditor
        - Administrator
        - SuperUser
    deployer:
      username: deployer
      password: deployer
      roles:
        - Deployer
    guest:
      username: guest
      password: guest
      roles:
        - viewer
    amq:
      username: amq
      password: karaf
      roles:
        - viewer
        - Administrator

# Network of Brokers Multicast
nob_multicast_name: default

## Setup for Applications and Bundles

# Applications Home
APP_HOME: '/opt/fuse/applications'

# Maven Repository
maven_repository_manager: http://rhel7jboss01:8081/nexus/content/groups/public

# Application List to deploy
applications:
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-consumer
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-producer
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-forwarder
    version: 1.1.0-SNAPSHOT

# Application List to undeploy
applications_undeploy:
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-consumer
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-producer
    version: 1.1.0-SNAPSHOT
  -
    groupId: com.redhat.camel
    artifactId: camel-amq-forwarder
    version: 1.1.0-SNAPSHOT
