---
- name: Download Application from Maven Repository
  become_user: "{{ user['name'] }}"
  maven_artifact:
    group_id: '{{ item.groupId }}'
    artifact_id: '{{ item.artifactId }}'
    version: '{{ item.version }}'
    repository_url: '{{ maven_repository_manager }}'
    dest: '{{ app_home }}/'
  with_items: '{{ applications }}'

- name: Create Applications Config in {{ FUSE_HOME }}/etc folder
  become_user: "{{ user['name'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ FUSE_HOME }}/etc/com.redhat.camel.environment.cfg"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
  with_items:
    - 'com.redhat.camel.environment.cfg.j2'

- name: Install Applications in {{ FUSE_HOME }}/deploy folder
  become_user: "{{ user['name'] }}"
  copy:
    src: "{{ app_home }}/{{ item.artifactId }}-{{ item.version }}.jar"
    remote_src: True
    dest: "{{ FUSE_HOME }}/deploy"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
  with_items: '{{ applications }}'

- name: Install Feature Repositories
  become_user: "{{ user['name'] }}"
  command: "{{ fuse_client}} 'features:addurl mvn:{{ item.groupId }}/{{ item.artifactId }}/{{ item.version }}/xml/features'"
  with_items: '{{ features }}'

- name: Install Features
  become_user: "{{ user['name'] }}"
  command: "{{ fuse_client}} 'features:install {{ item.name }}'"
  with_items: '{{ features }}'

- name: Install Bundles
  become_user: "{{ user['name'] }}"
  command: "{{ fuse_client}} 'osgi:install -s mvn:{{ item.groupId }}/{{ item.artifactId }}/{{ item.version }}'"
  with_items: '{{ bundles }}'
