---
- name: Install Playbook of a Fuse Standalone Environment
  hosts: fuse-lab-os1
  serial: 1
  remote_user: cloud-user
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
    # Two Fuse Standalone with A-MQ in Master/Slave topology with a Network of Brokers
    - { role: fuse-standalone, esb_name: 'esb01',  port_offset: '0', esb_type: 'full', nob: 'true', amq_master_slave: 'true' }
    - { role: fuse-standalone, esb_name: 'esb02',  port_offset: '100', esb_type: 'full', nob: 'true', amq_master_slave: 'true' }
    # Fuse Standalone with full profile and without a Network of Brokers
    - { role: fuse-standalone, esb_name: 'esb03',  port_offset: '200', esb_type: 'full', nob: 'false' }
    # Fuse Standalone without A-MQ
    - { role: fuse-standalone, esb_name: 'esb04',  port_offset: '300', esb_type: 'noamq', nob: 'false' }
    # Two Fuse Standalone without a Network of Brokers
    # - { role: fuse-standalone, esb_name: 'esb01',  port_offset: '0', nob: 'false' }
    # - { role: fuse-standalone, esb_name: 'esb02',  port_offset: '100', nob: 'false' }
    # One Fuse Standalone with Full profiles and One Fuse Standalone without A-MQ profile
    # - { role: fuse-standalone, esb_name: 'esb01',  port_offset: '0', nob: 'true' }
    # - { role: fuse-standalone, esb_name: 'esb02',  port_offset: '100', esb_type: 'noamq' }
