---
- name: Remove Applications from {{ fuse_home }}/deploy folder
  become_user: "{{ user['name'] }}"
  file:
    path: "{{ fuse_home }}/deploy/{{ item.artifactId }}-{{ item.version }}.jar"
    state: absent
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
  with_items: '{{ applications_undeploy }}'
  notify:
    - restart fuse-{{ esb_name }}

- name: Uninstall Features
  become_user: "{{ user['name'] }}"
  command: "{{ fuse_client}} 'features:uninstall {{ item.name }}'"
  with_items: '{{ features_undeploy }}'
  notify:
    - restart fuse-{{ esb_name }}

- name: Uninstall Feature Repositories
  become_user: "{{ user['name'] }}"
  command: "{{ fuse_client}} 'features:removeurl mvn:{{ item.groupId }}/{{ item.artifactId }}/{{ item.version }}/xml/features'"
  with_items: '{{ features_undeploy }}'

- name: Uninstall Bundles
  become_user: "{{ user['name'] }}"
  command: "{{ fuse_client}} 'osgi:uninstall {{ item.groupId }}.{{ item.artifactId }}/{{ item.version | regex_replace('-', '.')}}'"
  with_items: '{{ bundles_undeploy }}'
  notify:
    - restart fuse-{{ esb_name }}
